name: Build, Test and Deploy

on:
    push:
      branches:
        - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]
  

jobs:
  test_build_deploy_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install dependencies 
        run: npm install

      - name: Check style
        run: npm run lint

      - name: Test
        run: npm run test
        env:
            TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
            SECRET: ${{secrets.SECRET}}

      - name: Build UI
        run: npm run build:ui

      - name: Setup Flyctl
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: flyctl deploy -a blogs-cicd
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify discord about success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: GitHub
          text: New build succesfully deployed
          description: to https://blogs-cicd.fly.dev/ by ${{ github.actor }}
          footer: 'Severity: Informational'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        
      - name: Notify discord about failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          username: GitHub
          text: Build failed
          description: commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].author.username }} broke the build :(
          footer: 'Severity: Error'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: test_build_deploy_job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  
        